sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
language: python
python:
    # python versions used in el7 SCL & supported fedora
    - "3.5"
    - "3.6"
env:
  - DB=postgres
addons:
    # postgres versions provided by el7 RHSCL (lowest supportable version)
    postgresql: "9.5"
services:
    - postgresql
    - redis-server
install: source .travis/install.sh
before_script: source .travis/before_script.sh
script: source .travis/script.sh
after_failure:
  - sh -c "cat ~/django_runserver.log"
  - sh -c "cat ~/resource_manager.log"
  - sh -c "cat ~/reserved_workers-1.log"
stages:
- name: test
- name: deploy
  if: tag =~ ^3.0.0*
jobs:
  include:
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: pulp
      password:
        secure: O/1r6kCPWggV5sjmFACgGeml1dgMy8w46ku3atUiXyK5gJIVexbTMIXgLkpfTSu58ODBGoaW+ML6SQmC1K+82Vjq1OMURfrhvzolgSBhREMfM9lNjA52SoKCLzq4ldP31pOy/z3Z9T76vAJOWF7uI80jd2QJ2p+p6h101REl1dk=
      on:
        tags: true
